import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("monthly_sales.csv")
plt.figure(figsize=(10, 5))
plt.plot(df['Month'], df['Sales'], marker='o', linestyle='-', color='blue')
plt.title("Monthly Sales (Line Plot)")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(10, 5))
plt.scatter(df['Month'], df['Sales'], color='red', marker='x')
plt.title("Monthly Sales (Scatter Plot)")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(10, 5))
plt.bar(df['Month'], df['Sales'], color='green')
plt.title("Monthly Sales (Bar Plot)")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
plt.figure(figsize=(8, 8))
plt.pie(df['Sales'], labels=df['Month'], autopct='%1.1f%%', startangle=90, colors=plt.cm.tab20.colors)
plt.title("Proportion of Monthly Sales (Pie Chart)")
plt.axis('equal')
plt.tight_layout()
plt.show()