import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("weather_data.csv")
print("Data Preview:")
print(df)
plt.figure(figsize=(10, 5))
plt.plot(df["Month"], df["Temperature (°C)"], marker='o', label='Temperature (°C)', color='orange')
plt.plot(df["Month"], df["Rainfall (mm)"], marker='s', label='Rainfall (mm)', color='blue')
plt.title("Monthly Temperature and Rainfall")
plt.xlabel("Month")
plt.ylabel("Value")
plt.xticks(rotation=45)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(6, 5))
plt.scatter(df["Temperature (°C)"], df["Rainfall (mm)"], color='green')
plt.title("Temperature vs Rainfall")
plt.xlabel("Temperature (°C)")
plt.ylabel("Rainfall (mm)")
plt.grid(True)
plt.tight_layout()
plt.show()
